### ISSUE TITLE
I get invalid config

### ISSUE THREAD

**Issue by andreanilorenzo** [h4de5/home-assistant-vimar#1]
In Check Configuration i get:

`Invalid config for [vimar_platform]: [username] is an invalid option for [vimar_platform]. Check: vimar_platform->username. (See ?, line ?). `

This is che config:

```
vimar_platform:
  username: homeassistant
  password: pasw
  host: 192.168.1.4
  schema: https
  port: 443
```
