### ISSUE TITLE
My Vimar WebServer config file

### ISSUE THREAD

**Issue by andreanilorenzo** [h4de5/home-assistant-vimar#2]
I attach my configuration file to be imported on the Vimar WebServer.
If it could serve as a reference and test for the information it contains.

[Vimar WebServer.zip](https://github.com/h4de5/home-assistant-vimar/files/4742929/Vimar.WebServer.zip)

**Comment by h4de5** [comment]
Thank you for the insights. I found some translations that will come useful.
Do you still have an error or a warning message in the logs?

**Comment by andreanilorenzo** [comment]
For now i can't use

configuration.yaml:
```
vimar_platform:
  host: 192.168.1.2
  password: *********
  username: homeassistant
  schema: https
  port: 443
```

```
Configurazione non valida
Invalid config for [vimar_platform]: [host] is an invalid option for [vimar_platform]. Check: vimar_platform->host. (See ?, line ?). 
```

The githuf file is cloned in: /config/custom_components/vimar_platform

but i can't see in the log:

`........ WARNING (MainThread) [homeassistant.loader] You are using a custom integration for `
