### ISSUE TITLE
Energy monitor - energy entities set up as power domain and kW unit

### ISSUE THREAD

**Issue by marcogeni** [h4de5/home-assistant-vimar#23]
Hello Andi, first of all I'm very happy with you integration, almost all is functioning (except KNX variables that aren't added)
I would like to inform you that all the entities regarding the Energy monitor are imported as Power (kW unit) also those that are referred to Energy domain (kWh).
This is the list of entities imported from the Vimar web server:

- sensor.carichi_globale_controllo_autoconsumo_totale
- sensor.carichi_globale_controllo_autoconsumo_totale_2
- sensor.carichi_globale_controllo_consumo_totale
- sensor.carichi_globale_controllo_consumo_totale_2
- sensor.carichi_globale_controllo_custom_date
- sensor.carichi_globale_controllo_custom_date_2
- sensor.carichi_globale_controllo_custom_datetime
- sensor.carichi_globale_controllo_custom_datetime_2
- sensor.carichi_globale_controllo_custom_time
- sensor.carichi_globale_controllo_custom_time_2
- sensor.carichi_globale_controllo_energia_totale_consumo
- sensor.carichi_globale_controllo_energia_totale_consumo_2
- sensor.carichi_globale_controllo_energia_totale_immissione
- sensor.carichi_globale_controllo_energia_totale_prelievo
- sensor.carichi_globale_controllo_energia_totale_produzione
- sensor.carichi_globale_controllo_energia_totale_produzione_2
- sensor.carichi_globale_controllo_energia_totale_scambio
- sensor.carichi_globale_controllo_energia_totale_scambio_2
- sensor.carichi_globale_controllo_fase
- sensor.carichi_globale_controllo_fase_2
- sensor.carichi_globale_controllo_immissione_totale
- sensor.carichi_globale_controllo_immissione_totale_2
- sensor.carichi_globale_controllo_prelievo_totale
- sensor.carichi_globale_controllo_prelievo_totale_2
- sensor.carichi_globale_controllo_produzione_presente
- sensor.carichi_globale_controllo_produzione_presente_2
- sensor.carichi_globale_controllo_produzione_totale
- sensor.carichi_globale_controllo_produzione_totale_2
- sensor.carichi_globale_controllo_scambio_totale
- sensor.carichi_globale_controllo_scambio_totale_2

In my case, non every entity has data (maybe depends on my particular config).
Apart from *_custom_* (date/time) and *_fase* (don't know precisely, maybe phase check), all the entities have kW as unit of measure, also those referred to energy field (all the entities with_energia_ inside), that would have kWh.

In my case I corrected it through customize function:

```
 sensor.carichi_globale_controllo_energia_totale_consumo:
    device_class: energy
    unit_of_measurement: kWh
 sensor.carichi_globale_controllo_energia_totale_immissione:
    device_class: energy
    unit_of_measurement: kWh
 sensor.carichi_globale_controllo_energia_totale_prelievo:
    device_class: energy
    unit_of_measurement: kWh
 sensor.carichi_globale_controllo_energia_totale_produzione:
    device_class: energy
    unit_of_measurement: kWh
 sensor.carichi_globale_controllo_energia_totale_scambio:
    device_class: energy
    unit_of_measurement: kWh
 sensor.climatizzatori_energia_parziale:
    device_class: energy
    unit_of_measurement: kWh
```

I don't know if it's only my issue or is generalized, but maybe you could solve it at the origin.
I read the guidelines, but didn't follow it, if you need it I could try to do it.

Best regards, Marco
